Repository codestates-seb/seb45_pre_009, pull requests merged in 2023-08, with the labels that each got.

#23 json-server 대강
  client/json-server/.gitignore
  client/json-server/README.md
  client/json-server/db.json
  client/json-server/package-lock.json
  client/json-server/package.json
  client/package-lock.json
  client/package.json
Labels: [FE] 서강의, 세팅

#24 ✨ 카카오로그인 컴포넌트
  client/json-server/.gitignore
  client/json-server/README.md
  client/json-server/db.json
  client/json-server/package-lock.json
  client/json-server/package.json
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Login/GoogleLogin.js
  client/src/components/Login/GoogleUserInfo.js
  client/src/components/Login/KakaoLogin.js
  client/src/components/Login/KakaoUserInfo.js
Labels: [FE] 김진현, 기능

#28 Mainpage 임시
  client/dist/output.css
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.js
  client/src/api/api.js
  client/src/css/input.css
  client/src/index.js
  client/src/pages/main.js
  client/src/slicer/main.js
  client/src/store/store.js
  client/tailwind.config.js
Labels: [FE] 강소이, [FE] 김진현, [FE] 서강의, 기능

#22 [BE] Question CRUD 구현
  server/build.gradle
  server/src/main/java/com/gujo/stackoverflow/comment/controller/CommentController.java
  server/src/main/java/com/gujo/stackoverflow/comment/dto/CommentDto.java
  server/src/main/java/com/gujo/stackoverflow/comment/entity/Comment.java
  server/src/main/java/com/gujo/stackoverflow/comment/mapper/CommentMapper.java
  server/src/main/java/com/gujo/stackoverflow/comment/repository/CommentRepository.java
  server/src/main/java/com/gujo/stackoverflow/comment/service/CommentService.java
  server/src/main/java/com/gujo/stackoverflow/question/controller/QuestionController.java
  server/src/main/java/com/gujo/stackoverflow/question/dto/QuestionDto.java
  server/src/main/java/com/gujo/stackoverflow/question/entity/Question.java
  server/src/main/java/com/gujo/stackoverflow/question/mapper/QuestionMapper.java
  server/src/main/java/com/gujo/stackoverflow/question/repository/QuestionRepository.java
  server/src/main/java/com/gujo/stackoverflow/question/service/QuestionService.java
Labels: [BE] 서정욱, 기능

#34 ✨ 회원가입, 로그인
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Login/GoogleLogin.js
  client/src/components/Login/GoogleUserInfo.js
  client/src/components/Login/KakaoLogin.js
  client/src/components/Login/KakaoUserInfo.js
  client/src/components/Login/NormalLogin.js
  client/src/components/Login/SignIn.js
  client/src/images/Kakao.png
  client/src/images/badgesicon.png
  client/src/images/google.png
  client/src/images/questionicon.png
  client/src/images/tagicon.png
  client/src/images/votingicon.png
  client/src/index.css
  client/src/pages/LoginPage.js
  client/src/pages/SignUpPage.js
  client/tailwind.config.js
Labels: [FE] 강소이, [FE] 김진현, [FE] 서강의, 기능

#35 fe mainpage
  client/dist/output.css
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.js
  client/src/api/api.js
  client/src/css/input.css
  client/src/index.js
  client/src/pages/main.js
  client/src/slicer/main.js
  client/src/store/store.js
Labels: [FE] 강소이, [FE] 김진현, [FE] 서강의, 기능

#41 ✨ JWT 구현
  server/build.gradle
  server/src/main/java/com/gujo/stackoverflow/answer/dto/AnswerDto.java
  server/src/main/java/com/gujo/stackoverflow/answer/entity/Answer.java
  server/src/main/java/com/gujo/stackoverflow/answer/service/AnswerService.java
  server/src/main/java/com/gujo/stackoverflow/auth/dto/LoginDto.java
  server/src/main/java/com/gujo/stackoverflow/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/gujo/stackoverflow/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/gujo/stackoverflow/auth/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/com/gujo/stackoverflow/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/com/gujo/stackoverflow/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/gujo/stackoverflow/auth/userdetails/MemberDetailsService.java
  server/src/main/java/com/gujo/stackoverflow/auth/utils/CustomAuthorityUtils.java
  server/src/main/java/com/gujo/stackoverflow/config/SecurityConfiguration.java
  server/src/main/java/com/gujo/stackoverflow/member/entity/Member.java
  server/src/main/java/com/gujo/stackoverflow/member/repository/MemberRepository.java
  server/src/main/java/com/gujo/stackoverflow/member/service/MemberService.java
  server/src/main/resources/application.yml
Labels: [BE] 설주연

#55 🎨요청사항 상당수 수정
  client/json-server/db.json
  client/package-lock.json
  client/src/App.js
  client/src/api/api.js
  client/src/components/Footer/Footer.css
  client/src/components/Header/Header.js
  client/src/components/Login/NormalLogin.js
  client/src/components/Login/SignIn.js
  client/src/components/Sidebar/Sidebar.css
  client/src/components/Sidebar/Sidebar.js
  client/src/pages/SignUpPage.js
  client/src/pages/ask.js
  client/src/pages/main.js
  client/src/pages/questions.js
Labels: [FE] 강소이, [FE] 김진현, [FE] 서강의, 기능, 세팅

#73 마이페이지 구현
  client/src/components/Login/NormalLogin.js
  client/src/components/Mypage/Activity.js
  client/src/components/Mypage/Profile.js
  client/src/components/Mypage/Saves.js
  client/src/components/Mypage/Settings.js
  client/src/pages/Mypage.js
Labels: [FE] 강소이, [FE] 김진현, [FE] 서강의, 기능

#83 ✨마지막 저장
  client/json-server/db.json
  client/package-lock.json
  client/package.json
  client/src/api/api.js
  client/src/components/Sidebar/Sidebar.js
  client/src/components/comment/comment.js
  client/src/pages/Mypage.js
  client/src/pages/ask.js
  client/src/pages/main.js
  client/src/pages/questionpage.js
  client/src/pages/questions.js
  client/src/slicer/main.js
Labels: [FE] 강소이, [FE] 김진현, [FE] 서강의, 기능
